app_name = "awesome web"

log_level = "DEBUG"

[server]
protocols = ["http", "https", "port"]
ports = [10000, 10001, 10002]
timeout = "3s"

[mysql]
ip = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
database = "awesome"

[redis]
ip = "127.0.0.1"
#port = 6379