version: "3"
services:
  imaginary:
    image: h2non/imaginary:latest
    # optionally mount a volume as local image source
    volumes:
      - images:/mnt/data
    environment:
      PORT: 9000
    command: -enable-url-source -mount /mnt/data
    ports:
      - "9000:9000"
